"""empty message

Revision ID: 37f68f2608d5
Revises: 4107d01229c7
Create Date: 2025-07-09 17:18:08.978236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f68f2608d5'
down_revision = '4107d01229c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consola_videojuego', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_videojuego', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'videojuego', ['id_videojuego'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consola_videojuego', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_videojuego')

    # ### end Alembic commands ###
