"""empty message

Revision ID: 4107d01229c7
Revises: 9747584d7ed5
Create Date: 2025-07-09 17:16:39.078181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4107d01229c7'
down_revision = '9747584d7ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consola_videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_consola', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_consola'], ['consola.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consola_videojuego')
    # ### end Alembic commands ###
