"""empty message

Revision ID: 77abdaba8933
Revises: 13389dc7cbdb
Create Date: 2025-07-09 17:21:04.976555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77abdaba8933'
down_revision = '13389dc7cbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
