"""empty message

Revision ID: 994b98c3c140
Revises: c50b90c3c0a7
Create Date: 2025-07-09 16:50:58.437234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994b98c3c140'
down_revision = 'c50b90c3c0a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videojuego',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videojuego')
    # ### end Alembic commands ###
