"""empty message

Revision ID: c50b90c3c0a7
Revises: bb09bc736d28
Create Date: 2025-07-09 16:49:38.753103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50b90c3c0a7'
down_revision = 'bb09bc736d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('slogan', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empresa')
    # ### end Alembic commands ###
